# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
name: "build"

on:
  push:
    branches:
      - tcc-1.21*
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_call:
    inputs:
      build_fips:
        description: 'Build FIPS-compliant version'
        type: boolean
        default: false
        required: false

env:
  BUILD_FIPS: ${{ inputs.build_fips }}
  # below variables are used to pull envoy binary from GCS bucket

  # ENVOY_PROXY_GCA_BUCKET_URL_FROM_TID_FIPS needs to be updated only if the URL changes in future
  ENVOY_PROXY_GCA_BUCKET_URL_FROM_TID_FIPS: 'https://storage.googleapis.com/tetrate-istio-subscription-build/proxy-fips'

  # ENVOY_PROXY_SHA_FROM_TID_FIPS needs to be specified when FIPS build should use a different version
  # of Istio Proxy (Envoy) than non-FIPS build.
  # In general, we want to reuse FIPS version of Istio Proxy (Envoy) built for TID.
  # To achieve that, use SHA from the build manifest of a release in tetrateio/tis-releases/releases.
  ENVOY_PROXY_SHA_FROM_TID_FIPS: 'bcf6c19288e9d4a133f815657c951539018bc9bb' # TID 1.21.2+3

jobs:

  config:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.config.outputs.image }}
      tag: ${{ steps.git.outputs.tag }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - id: config
        run: |
          source common/scripts/setup_env.sh
          echo "::set-output name=image::${IMG}" # ISTIO_BUILD_TOOLS
      - id: git
        run: |
          TAG=
          if [[ "${GITHUB_REF:-}" == refs/tags/* ]]; then
            TAG=$( echo "${GITHUB_REF}" | tail -c +11 )
          fi
          if [[ "${TAG}" != "" && "${BUILD_FIPS:-false}" == "true" ]]; then
            TAG="${TAG}-fips"
          fi
          echo "::set-output name=tag::${TAG}"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history for all tags and branches

      - run: make -e T=-v build binaries-test

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - run: make -e T="-v -count=1" init racetest

  release:
    needs: config
    runs-on: [self-hosted, linux, x64, arc] # we use a self-host runner here to get more disk space

    container:
      image: ${{ needs.config.outputs.image }} # ISTIO_BUILD_TOOLS
      env:
        BUILD_WITH_CONTAINER: "0"
        GOOGLE_APPLICATION_CREDENTIALS: /gcs.key.json

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history for all tags and branches

      - name: "Fix git commands failing with 'fatal: unsafe repository (... is owned by someone else)'"
        # see https://github.com/actions/checkout/issues/766
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: "Docker login"
        env:
          DOCKER_HUB_USER: ${{ secrets.TETRATE_CI_DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.TETRATE_CI_DOCKER_HUB_PASSWORD }}
        run: docker login --username "${DOCKER_HUB_USER}" --password "${DOCKER_HUB_PASSWORD}"

      - name: "GCS Credentials"
        env:
          GCS_CREDENTIALS: ${{ secrets.TETRATE_CI_GCS_CREDENTIALS }}
        run: |
          echo "${GCS_CREDENTIALS}" | base64 -d > ${GOOGLE_APPLICATION_CREDENTIALS}
          gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
      - env:
          DOCKER_HUB: ${{ secrets.TETRATE_CI_DOCKER_HUB }}
          GCS_BUCKET: ${{ secrets.TETRATE_CI_GCS_BUCKET }}
          PUBLISH_GCS_ALIASES: "0" # don't publish aliases to GCS
          VERSION: ${{ needs.config.outputs.tag }}
          ISTIO_ENVOY_BASE_URL: ${{ env.BUILD_FIPS == 'true' && env.ENVOY_PROXY_GCA_BUCKET_URL_FROM_TID_FIPS || '' }}
          PROXY_REPO_SHA: ${{ env.BUILD_FIPS == 'true' && env.ENVOY_PROXY_SHA_FROM_TID_FIPS || '' }}
        run: prow/release-commit.sh

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - run: make lint

  gencheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - run: make gen-check

  analyze-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - run: make test.integration.analyze
